[package]
name = "ruffle_render_skia"
version = "0.1.0"
authors = ["Callum Thomson <callumthom11@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
ruffle_render_common_tess = { path = "../common_tess" }
winit = "0.25.0"
skia-safe = "0"
raw-window-handle = "0.3.3"
x11 = { version = "2.18.2", features = ["xlib"] }
png = "0.17.0"
blit = { path = "/home/cub3d/projects/raw_blit/blit"}

[dependencies.ruffle_core]
path = "../../core"
default-features = false
